apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: multi-container
  labels:
    app: multi
  annotations:
    cs1660.pitt.edu/app: multi
spec:
  containers:
  - name: alpine 
    image: alpine:3.12
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  - name: dnsutils
    image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
